"""add price to shopping item

Revision ID: e7b95339b35e
Revises: 03fa8ecb22e5
Create Date: 2026-05-15 15:07:56.866208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b95339b35e'
down_revision = '03fa8ecb22e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
