"""add checked_week and checked_year to shopping_item

Revision ID: e858fb3bfdf0
Revises: c40a77c63be0
Create Date: 2026-06-04 11:08:13.592628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e858fb3bfdf0'
down_revision = 'c40a77c63be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_week', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checked_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_items', schema=None) as batch_op:
        batch_op.drop_column('checked_year')
        batch_op.drop_column('checked_week')

    # ### end Alembic commands ###
